(() => {
  const state = {data:null, saved:{jobs:{},companies:{},customCompanies:{},customJobs:{},meta:{seen:{},newOpportunities:{}}}, candidate:"Vaanya", route:"home", visibleCompanyLimit:12};
  const $ = id => document.getElementById(id);
  const statuses = ["Not started","Watching","Applied","Interviewing","Offer","Closed"];
  const domains = {uber:"uber.com",zomato:"zomato.com",atlassian:"atlassian.com",adobe:"adobe.com",amazon:"amazon.jobs","amazon payments":"amazon.jobs",apple:"apple.com",google:"google.com",meta:"meta.com",flipkart:"flipkart.com",salesforce:"salesforce.com",stripe:"stripe.com",rippling:"rippling.com",razorpay:"razorpay.com",qualcomm:"qualcomm.com",uipath:"uipath.com",zepto:"zeptonow.com",swiggy:"swiggy.com",paytm:"paytm.com",phonepe:"phonepe.com","pine labs":"pinelabs.com","goldman sachs":"goldmansachs.com","d e shaw":"deshaw.com","de shaw":"deshaw.com","tower research capital":"tower-research.com",citi:"citi.com",citicorp:"citi.com","palo alto":"paloaltonetworks.com","palo alto networks":"paloaltonetworks.com","info edge":"infoedge.in",infoedge:"infoedge.in",visa:"visa.com",netflix:"netflix.com",walmart:"walmart.com",microsoft:"microsoft.com",linkedin:"linkedin.com",servicenow:"servicenow.com","service now":"servicenow.com",crowdstrike:"crowdstrike.com",databricks:"databricks.com",rubrik:"rubrik.com",mongodb:"mongodb.com",freshworks:"freshworks.com",agoda:"agoda.com",cred:"cred.club",snowflake:"snowflake.com",cisco:"cisco.com",zscaler:"zscaler.com","mckinsey & company":"mckinsey.com","bain & company":"bain.com","american express":"americanexpress.com","media.net":"media.net",deloitte:"deloitte.com","morgan stanley":"morganstanley.com","jp morgan":"jpmorganchase.com","hacker rank":"hackerrank.com",hackerrank:"hackerrank.com","pocket fm":"pocketfm.com",gupshup:"gupshup.io","attentive.ai":"attentive.ai","publicis sapient":"publicissapient.com","play simple":"playsimple.in",ema:"ema.co",glean:"glean.com",instawork:"instawork.com","squarepoint capital":"squarepoint-capital.com","exl service":"exlservice.com","par technology":"partech.com",mthree:"mthree.com",weekday:"weekday.works",okta:"okta.com",cvent:"cvent.com",colt:"colt.net",barco:"barco.com",commvault:"commvault.com",navigus:"navigus.in",zopsmart:"zopsmart.com"};
  const esc = value => String(value ?? "").replace(/[&<>"']/g, ch => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[ch]));
  const norm = value => String(value || "").trim().toLocaleLowerCase().replace(/[.,]/g, "").replace(/\s+/g, " ");
  const companyKey = (candidate,name) => `${candidate}:${norm(name)}`;
  const roleKey = (candidate,job) => `${candidate}:${jobIdentity(job)}`;
  const profile = candidate => state.data.profiles.find(item => item.candidate === candidate);
  const nowISODate = () => { const d=new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`; };
  const dateLabel = value => { if(!value)return "Not recorded"; const d=new Date(`${value}T00:00:00`);return Number.isNaN(+d)?value:d.toLocaleDateString(undefined,{day:"numeric",month:"short",year:"numeric"}); };
  const normalizedStatus = value => statuses.includes(value) ? value : "Not started";
  function routeFromPath(){const path=location.pathname.replace(/\/+$/g,"");if(["/apply","/today","/hunt"].includes(path)){state.applyTab=path==="/hunt"?"choose":path==="/today"?"picks":null;return "apply";}return ["/vaanya","/vrinda","/person","/home"].includes(path)?path.slice(1):"home";}
  function goRoute(route){location.href=`/${route}`;}
  function jobIdentity(job){
    if(job.url){try{const u=new URL(job.url);const q=["jk","gh_jid","jobid","job_id","requisitionid","reqid","folderid","id"].map(k=>[k,u.searchParams.get(k)]).filter(x=>x[1]).map(x=>x.join("=")).join("&");return `url:${u.hostname.toLowerCase()}${u.pathname.replace(/\/$/,"")}${q?"?"+q:""}`;}catch{}}
    return `role:${norm(job.company)}|${norm(job.title)}|${norm(job.location)}`;
  }
  function sourceJobs(candidate){return profile(candidate)?.jobs||[];}
  function customJobs(candidate){return Object.values(state.saved.customJobs||{}).filter(job=>job.candidate===candidate);}
  function allJobs(candidate){return [...sourceJobs(candidate),...customJobs(candidate)];}
  function jobState(job,candidate=state.candidate){return state.saved.jobs[roleKey(candidate,job)]||{};}
  function jobStatus(job,candidate=state.candidate){return normalizedStatus(jobState(job,candidate).status||job.status);}
  function getContacts(candidate,company){
    const p=profile(candidate);const found=[];
    for(const contact of p?.contacts||[])if(norm(contact.company)===norm(company))found.push(contact);
    const roster=(p?.companies||[]).find(item=>norm(item.name)===norm(company));
    for(const value of roster?.contacts||[])found.push(typeof value==="string"?{company,name:value,title:"",source_sheet:"Company tracker"}:value);
    const custom=state.saved.customCompanies[companyKey(candidate,company)];
    for(const name of custom?.contacts||[])found.push({company,name,title:"Added in dashboard",source_sheet:"Dashboard"});
    const seen=new Set();return found.filter(c=>c.name&&!/^(no\s+(contact|referral)|none|n\/a|na|nil|tbd|unknown|-+)\b/i.test(String(c.name).trim())&&!seen.has(norm(c.name))&&seen.add(norm(c.name)));
  }
  function companyRecords(candidate){
    const map=new Map();
    for(const item of profile(candidate)?.companies||[])map.set(norm(item.name),{name:item.name,sourceStatus:item.status||"",tracking:item.tracking||"",sheetNotes:item.notes||"",sheetTags:item.tags||[],jobs:[],source:"tracker"});
    for(const custom of Object.values(state.saved.customCompanies||{}).filter(x=>x.candidate===candidate)){const key=norm(custom.name);if(!map.has(key))map.set(key,{name:custom.name,sourceStatus:"",jobs:[],source:"custom"});map.get(key).custom=custom;}
    for(const job of allJobs(candidate)){const key=norm(job.company);if(!map.has(key))map.set(key,{name:job.company,sourceStatus:"",jobs:[],source:"roles"});map.get(key).jobs.push(job);}
    for(const company of map.values())company.contacts=getContacts(candidate,company.name);
    return [...map.values()];
  }
  function logo(name){
    const key=norm(name);const slug=key.replace(/\b(inc|incorporated|limited|ltd|corporation|corp|technologies|technology|systems|company|group)\b/g,"").trim().replace(/[^a-z0-9]+/g,"");
    const domain=domains[key]||`${slug||"example"}.com`;const initials=esc(name.split(/\s+/).slice(0,2).map(x=>x[0]||"").join("").toUpperCase());
    return `<span class="company-logo"><img loading="lazy" src="https://www.google.com/s2/favicons?domain=${encodeURIComponent(domain)}&sz=64" alt="" onerror="this.parentElement.classList.add('fallback');this.remove();this.parentElement.textContent='${initials}'"></span>`;
  }
  function isDrive(job){return job.category==="Hiring drive";}
  function isHistorical(job){return job.category==="Historical / wave role";}
  function jobUrl(job){const value=String(job.url||job.notes||"");const match=value.match(/https?:\/\/[^\s<>"']+/i);return match?match[0].replace(/[),.;]+$/,""):"";}
  function isLinkedIn(job){try{return new URL(jobUrl(job)).hostname.toLowerCase().replace(/^www\./,"").endsWith("linkedin.com");}catch{return false;}}
  function isNew(job,candidate=state.candidate){const stamp=state.saved.meta?.newOpportunities?.[roleKey(candidate,job)];if(!stamp)return false;return Date.now()-new Date(stamp).getTime()<30*86400000;}
  function contactPills(contacts){return contacts.length?contacts.map(c=>{const hr=/hr|talent|recruit|people operations/i.test(`${c.title||""} ${c.function||""} ${c.name||""}`);return `<span class="referral-pill ${hr?"hr":""}" title="${esc(c.title||c.function||c.source_sheet||"")}">${esc(c.name)}${hr?" · HR/TA":""}</span>`}).join(""):`<span class="no-referral">No referral contact in tracker</span>`;}
  function statusOptions(value){return statuses.map(s=>`<option ${s===value?"selected":""}>${s}</option>`).join("");}
  function tag(job,candidate){const fresh=isNew(job,candidate);return `${fresh?'<span class="tiny-chip new-chip">NEW</span>':""}<span class="tiny-chip ${isDrive(job)?"drive":""} ${isHistorical(job)?"historical":""}">${esc(job.category||"Role")}</span>${job.experience?`<span class="tiny-chip">${esc(job.experience)}</span>`:""}${job.compensation?`<span class="tiny-chip pay-chip">${esc(job.compensation)}</span>`:""}${job.score?`<span class="tiny-chip priority">Match ${esc(job.score)}</span>`:""}${(job.tags||[]).map(t=>`<span class="tiny-chip sheet-tag ${/reject|closed|not |deadline|invalid/i.test(t)?"bad":/referr|asked/i.test(t)?"ref":/applied|assessment/i.test(t)?"good":""}">${esc(t)}</span>`).join("")}`;}
  function renderRole(job,candidate){
    const key=roleKey(candidate,job),saved=jobState(job,candidate),contacts=getContacts(candidate,job.company),status=jobStatus(job,candidate);
    const appliedAt=saved.appliedAt||job.appliedAt||"";const note=saved.applicationNotes||"";const next=saved.nextStep||"";
    const sourceNote=job.notes?`<div class="role-source-note"><strong>Source sheet note</strong> · ${esc(job.notes)}</div>`:"";
    const url=jobUrl(job);
    return `<article class="role-card" data-role="${esc(jobIdentity(job))}"><div class="role-card-head"><div class="role-title-wrap"><div class="role-title">${esc(job.title||"Role title not listed")}</div><div class="role-tags">${tag(job,candidate)}</div></div><div class="role-status-wrap"><label class="sr-only" for="status-${esc(key)}">Status</label><select id="status-${esc(key)}" data-status="${esc(key)}" data-role-identity="${esc(jobIdentity(job))}">${statusOptions(status)}</select>${url?`<a class="open-link" href="${esc(url)}" target="_blank" rel="noopener noreferrer" title="Open source listing">Open ↗</a>`:`<span class="no-link">No link</span>`}</div></div>
      <div class="role-meta"><span>${esc(job.location||"Location not listed")}</span>${job.verification?`<span>${esc(job.verification)}</span>`:""}${job.status?`<span>Sheet status: ${esc(job.status)}</span>`:""}<span>${esc(job.source_sheet||"Source not stated")}</span></div>
      <div class="role-referrals"><span class="role-referral-label">WHO TO REACH OUT TO</span><div class="referral-stack">${contactPills(contacts)}</div></div>${sourceNote}
      <details class="role-tracking"><summary>Application notes & next step <span>${status==="Applied"?`Applied ${esc(dateLabel(appliedAt))}`:esc(status)}</span></summary><div class="tracking-fields"><label>Status<select data-status="${esc(key)}" data-role-identity="${esc(jobIdentity(job))}">${statusOptions(status)}</select></label><label>Date applied<input type="date" data-applied-at="${esc(key)}" value="${esc(appliedAt)}"></label><label class="tracking-wide">What should you remember?<textarea rows="2" data-application-notes="${esc(key)}" placeholder="Referral context, prep notes, details from the posting…">${esc(note)}</textarea></label><label class="tracking-wide">Next step<input data-next-step="${esc(key)}" value="${esc(next)}" placeholder="Ask referral contact, follow up, interview prep…"></label><button type="button" class="button button-quiet save-role-note" data-save-role="${esc(key)}">Save tracker details</button></div></details>
    </article>`;
  }
  function renderLinkedInJob(job,candidate){
    const contacts=getContacts(candidate,job.company),applied=jobStatus(job,candidate)==="Applied",url=jobUrl(job);
    return `<article class="linkedin-job">${logo(job.company)}<div class="linkedin-job-main"><div class="linkedin-company">${esc(job.company)}</div><strong>${esc(job.title||"LinkedIn opportunity")}</strong><div class="linkedin-meta">${esc(job.location||"Location not listed")}${job.experience?` · ${esc(job.experience)}`:""}</div>${(job.tags||[]).length?`<div class="agent-tags">${(job.tags||[]).map(t=>`<span class="tiny-chip sheet-tag">${esc(t)}</span>`).join("")}</div>`:""}${job.notes?`<div class="src-note"><b>From your sheet</b> · ${esc(job.notes.slice(0,140))}</div>`:""}<div class="referral-stack">${contactPills(contacts)}</div></div><a class="linkedin-open ${applied?"is-applied":""}" data-linkedin-apply="${esc(jobIdentity(job))}" href="${esc(url)}" target="_blank" rel="noopener noreferrer">${applied?"Applied · open ↗":"Open & mark Applied ↗"}</a></article>`;
  }
  function visibleCompanyRecords(candidate){
    const query=($("search")?.value||"").trim().toLocaleLowerCase(),filter=$("category-filter")?.value||"jobs",selected=$("company-filter")?.value||"";
    let items=companyRecords(candidate).map(company=>({...company,jobs:company.jobs.filter(job=>{
      if(isLinkedIn(job))return false;
      const all=[company.name,job.title,job.location,job.experience,job.compensation,job.notes,job.category,job.verification,...company.contacts.flatMap(c=>[c.name,c.title])].join(" ").toLocaleLowerCase();
      const qOk=!query||all.includes(query);const catOk=filter==="all"||(filter==="jobs"&&!isDrive(job)&&!isHistorical(job))||(filter==="drives"&&isDrive(job))||(filter==="new"&&isNew(job,candidate))||(filter==="referral"&&company.contacts.length>0);
      return qOk&&catOk;
    })})).filter(company=>(company.jobs.length||((!query||company.name.toLocaleLowerCase().includes(query))&&filter==="all"))&&(!selected||norm(company.name)===selected));
    const order=$("sort-order")?.value||"name";
    if(order==="roles")items.sort((a,b)=>b.jobs.filter(j=>!isDrive(j)&&!isHistorical(j)).length-a.jobs.filter(j=>!isDrive(j)&&!isHistorical(j)).length||a.name.localeCompare(b.name));
    else if(order==="new")items.sort((a,b)=>Math.max(...b.jobs.map(j=>new Date(state.saved.meta?.newOpportunities?.[roleKey(candidate,j)]||0).getTime()),0)-Math.max(...a.jobs.map(j=>new Date(state.saved.meta?.newOpportunities?.[roleKey(candidate,j)]||0).getTime()),0)||a.name.localeCompare(b.name));
    else items.sort((a,b)=>a.name.localeCompare(b.name));
    return items;
  }
  function renderCompany(company,candidate){
    const contacts=company.contacts;const savedCompany=state.saved.companies[companyKey(candidate,company.name)]||{};const jobs=[...company.jobs].sort((a,b)=>Number(isNew(b,candidate))-Number(isNew(a,candidate))||Number(isDrive(a))-Number(isDrive(b))||a.title.localeCompare(b.title));
    const roleCount=jobs.filter(j=>!isDrive(j)&&!isHistorical(j)).length,drives=jobs.filter(isDrive).length,historical=jobs.filter(isHistorical).length;
    return `<details class="company-group"><summary class="company-summary"><div class="company-identity">${logo(company.name)}<div><strong>${esc(company.name)}</strong><small>${company.source==="tracker"?"Company tracker":company.source==="custom"?"Added in dashboard":"From role records"}</small></div></div><div class="company-count"><strong>${roleCount}</strong><span>role${roleCount===1?"":"s"}</span>${drives?`<small>+ ${drives} drive${drives===1?"":"s"}</small>`:""}${historical?`<small>${historical} historical</small>`:""}</div><div class="company-referral-summary">${contacts.length?`<span class="referral-chip">↗ ${contacts.length} contact${contacts.length===1?"":"s"}</span>`:`<span class="referral-chip none">No contact</span>`}</div><label class="company-status-control" onclick="event.stopPropagation()"><span class="sr-only">Company status</span><select data-company-status="${esc(company.name)}">${statusOptions(normalizedStatus(savedCompany.status||company.tracking))}</select></label><span class="chevron">⌄</span></summary><div class="company-body"><div class="company-notes"><div class="company-body-heading"><span>REFERRAL / HR / TA</span><span>COMPANY NOTES</span></div><div class="referral-stack">${contactPills(contacts)}</div>${(company.sheetNotes||(company.sheetTags||[]).length)?`<div class="sheet-note"><b>From your company tracker</b>${(company.sheetTags||[]).map(t=>`<span class="tiny-chip sheet-tag">${esc(t)}</span>`).join("")}<p>${esc(company.sheetNotes||"")}</p></div>`:""}<div class="company-note-editor"><textarea rows="2" data-company-note="${esc(company.name)}" placeholder="What have you applied to? Who can refer you? Anything to remember…">${esc(savedCompany.note||company.custom?.note||"")}</textarea><button type="button" class="button button-quiet" data-save-company="${esc(company.name)}">Save note</button></div></div><div class="company-jobs">${jobs.map(job=>renderRole(job,candidate)).join("")||'<p class="empty-company">No role rows for this company yet. Refresh from the latest tracker export or add a role.</p>'}</div></div></details>`;
  }
  function renderOpeningPage(){
    const candidate=state.candidate,p=profile(candidate),directory=companyRecords(candidate),companySelect=$("company-filter"),selectedCompany=companySelect.value;
    companySelect.innerHTML=`<option value="">All companies with matches</option>${directory.slice().sort((a,b)=>a.name.localeCompare(b.name)).map(company=>`<option value="${esc(norm(company.name))}">${esc(company.name)}</option>`).join("")}`;
    if([...companySelect.options].some(option=>option.value===selectedCompany))companySelect.value=selectedCompany;
    const companies=visibleCompanyRecords(candidate),page=companies.slice(0,state.visibleCompanyLimit),jobs=allJobs(candidate),linkedinJobs=jobs.filter(isLinkedIn);const tracked=jobs.filter(j=>jobStatus(j,candidate)!=="Not started").length;const referrals=(p.companies||[]).filter(c=>getContacts(candidate,c.name).length).length;const newCount=jobs.filter(j=>isNew(j,candidate)).length;
    $("candidate-kicker").textContent=`${candidate.toUpperCase()} · ${candidate==="Vaanya"?"EARLY CAREER":"EXPERIENCED BACKEND / SDE"}`;
    $("candidate-title").innerHTML=`${candidate}’s openings<br><span class="gradient-word">by company.</span>`;
    $("candidate-description").textContent=candidate==="Vaanya"?"Graduate roles, early-career tracks and hiring drives from the latest tracker, with sources and referral context grouped under each employer.":"Backend and SDE roles from the latest tracker, grouped by employer with referral details and a place to keep application notes.";
    $("linkedin-section").classList.toggle("hidden",linkedinJobs.length===0);$("linkedin-count").textContent=`${linkedinJobs.length} link${linkedinJobs.length===1?"":"s"} · ${candidate}`;$("linkedin-results").innerHTML=linkedinJobs.map(job=>renderLinkedInJob(job,candidate)).join("");
    $("summary-grid").innerHTML=[[companyRecords(candidate).length,"Companies represented","tracker + role sources"],[jobs.length,"Role records","includes drives and historical rows"],[referrals,"Companies with contacts","from supplied tracker notes"],[newCount,"New this month","added on a refresh"]].map((x,i)=>`<article class="summary-card ${i===0?"summary-primary":i===2?"summary-lilac":""}"><div class="summary-label">${esc(x[1].toUpperCase())}<span>0${i+1}</span></div><div class="summary-value">${x[0]}</div><div class="summary-caption">${esc(x[2])}</div></article>`).join("");
    const matchingRows=companies.reduce((count,company)=>count+company.jobs.length,0);
    $("results-count").textContent=`Showing ${page.length} of ${companies.length} companies · ${matchingRows} matching records`;
    $("updated-label").textContent=`${state.data.source_mode==="live"?"Live Google Sheets":"Local workbook fallback"} · ${new Date(state.data.generated_at).toLocaleString()}`;
    $("results").innerHTML=page.map(c=>renderCompany(c,candidate)).join("");$("empty").classList.toggle("hidden",companies.length>0);$("results").classList.toggle("hidden",companies.length===0);
    const more=$("show-more-companies");more.classList.toggle("hidden",page.length>=companies.length);more.textContent=`Show next 12 companies · ${companies.length-page.length} left`;
    bindTrackerControls();
  }
  function isTracked(job,candidate){const s=jobState(job,candidate);return normalizedStatus(s.status||job.status)!=="Not started"||Boolean(s.appliedAt||s.applicationNotes||s.nextStep)||Boolean(job.manual);}
  function trackedList(candidate){
    const q=($("tracker-search")?.value||"").trim().toLocaleLowerCase(),filter=$("tracker-filter")?.value||"tracked";
    return allJobs(candidate).filter(job=>{const saved=jobState(job,candidate),status=jobStatus(job,candidate),hay=[job.company,job.title,job.location,job.notes,saved.applicationNotes,saved.nextStep,...getContacts(candidate,job.company).map(c=>c.name)].join(" ").toLocaleLowerCase();return (!q||hay.includes(q))&&(filter==="all"||filter==="tracked"&&isTracked(job,candidate)||filter==="applied"&&status==="Applied"||filter==="active"&&["Watching","Applied","Interviewing","Offer"].includes(status)||filter==="new"&&isNew(job,candidate));}).sort((a,b)=>{const ad=jobState(a,candidate).appliedAt||"9999",bd=jobState(b,candidate).appliedAt||"9999";return ad.localeCompare(bd)||a.company.localeCompare(b.company);});
  }
  function renderTracker(){
    const candidate=state.candidate,jobs=allJobs(candidate),tracked=jobs.filter(j=>isTracked(j,candidate)),applied=jobs.filter(j=>jobStatus(j,candidate)==="Applied"),active=jobs.filter(j=>["Watching","Interviewing","Offer"].includes(jobStatus(j,candidate))),fresh=jobs.filter(j=>isNew(j,candidate));
    $("tracker-candidate-switch").innerHTML=["Vaanya","Vrinda"].map(name=>`<button class="candidate-tab ${candidate===name?"active":""}" data-tracker-candidate="${name}">${name}</button>`).join("");
    $("tracker-summary").innerHTML=[[tracked.length,"Roles being tracked"],[applied.length,"Applied"],[active.length,"Watching / active"],[fresh.length,"New this month"]].map((x,i)=>`<article class="summary-card ${i===0?"summary-primary":i===3?"summary-lilac":""}"><div class="summary-label">${esc(x[1].toUpperCase())}<span>0${i+1}</span></div><div class="summary-value">${x[0]}</div><div class="summary-caption">${i===0?"across all companies":i===1?"application date can be edited":"in your local tracker"}</div></article>`).join("");
    const list=trackedList(candidate);$("tracker-count").textContent=`${list.length} roles · ${candidate}`;$("tracker-results").innerHTML=list.map(job=>{const url=jobUrl(job);return `<article class="tracker-row"><div class="tracker-company">${logo(job.company)}<strong>${esc(job.company)}</strong></div><div class="tracker-role"><strong>${esc(job.title)}</strong><small>${esc(job.location||"Location not listed")}</small>${(job.notes||(job.tags||[]).length)?`<small class="src-note"><b>From your sheet</b> · ${esc([...(job.tags||[]),job.notes?job.notes.slice(0,140):""].filter(Boolean).join(" · "))}</small>`:""}${url?`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">Open source ↗</a>`:""}</div><div class="tracker-date"><span>DATE APPLIED</span><input type="date" data-applied-at="${esc(roleKey(candidate,job))}" value="${esc(jobState(job,candidate).appliedAt||job.appliedAt||"")}"></div><div class="tracker-stage"><span>STAGE</span><select data-status="${esc(roleKey(candidate,job))}" data-role-identity="${esc(jobIdentity(job))}">${statusOptions(jobStatus(job,candidate))}</select></div><div class="tracker-notes"><label>Notes to remember<textarea data-application-notes="${esc(roleKey(candidate,job))}" rows="2" placeholder="Interview notes, referral context, what mattered when applying…">${esc(jobState(job,candidate).applicationNotes||"")}</textarea></label><label>Next step<input data-next-step="${esc(roleKey(candidate,job))}" value="${esc(jobState(job,candidate).nextStep||"")}" placeholder="Follow up with…"></label><button type="button" class="button button-quiet save-role-note" data-save-role="${esc(roleKey(candidate,job))}">Save changes</button></div></article>`;}).join("");
    $("tracker-empty").classList.toggle("hidden",list.length>0);$("tracker-results").classList.toggle("hidden",list.length===0);bindTrackerControls();
  }
  function bindTrackerControls(){
    document.querySelectorAll("[data-linkedin-apply]").forEach(link=>link.addEventListener("click",()=>{const identity=link.dataset.linkedinApply,job=allJobs(state.candidate).find(item=>jobIdentity(item)===identity);if(!job)return;const key=roleKey(state.candidate,job),old=jobState(job),date=old.appliedAt||nowISODate();state.saved.jobs[key]={...old,candidate:state.candidate,status:"Applied",appliedAt:date,appliedVia:"LinkedIn listing opened",updatedAt:new Date().toISOString()};link.textContent="Opened · Applied ✓";link.classList.add("is-applied");persist();}));
    document.querySelectorAll("[data-status]").forEach(el=>el.addEventListener("change",e=>{const key=e.currentTarget.dataset.status,identity=e.currentTarget.dataset.roleIdentity;const found=allJobs(state.candidate).find(job=>jobIdentity(job)===identity);if(!found)return;const old=jobState(found);const status=e.currentTarget.value;state.saved.jobs[key]={...old,candidate:state.candidate,status,appliedAt:status==="Applied"?(old.appliedAt||nowISODate()):old.appliedAt,updatedAt:new Date().toISOString()};persist();state.route==="person"?renderTracker():renderOpeningPage();}));
    document.querySelectorAll("[data-applied-at]").forEach(el=>el.addEventListener("change",e=>{const key=e.currentTarget.dataset.appliedAt,old=state.saved.jobs[key]||{};state.saved.jobs[key]={...old,candidate:state.candidate,appliedAt:e.currentTarget.value,updatedAt:new Date().toISOString()};persist();}));
    document.querySelectorAll("[data-save-role]").forEach(btn=>btn.addEventListener("click",()=>{const key=btn.dataset.saveRole;const note=document.querySelector(`[data-application-notes="${CSS.escape(key)}"]`)?.value||"",next=document.querySelector(`[data-next-step="${CSS.escape(key)}"]`)?.value||"",date=document.querySelector(`[data-applied-at="${CSS.escape(key)}"]`)?.value||"";state.saved.jobs[key]={...(state.saved.jobs[key]||{}),candidate:state.candidate,applicationNotes:note,nextStep:next,appliedAt:date,updatedAt:new Date().toISOString()};persist();btn.textContent="Saved ✓";setTimeout(()=>{if(btn.isConnected)btn.textContent="Save changes";},1200);}));
    document.querySelectorAll("[data-save-company]").forEach(btn=>btn.addEventListener("click",()=>{const name=btn.dataset.saveCompany,key=companyKey(state.candidate,name),note=document.querySelector(`[data-company-note="${CSS.escape(name)}"]`)?.value||"";state.saved.companies[key]={...(state.saved.companies[key]||{}),candidate:state.candidate,company:name,note,updatedAt:new Date().toISOString()};persist();btn.textContent="Saved ✓";setTimeout(()=>{if(btn.isConnected)btn.textContent="Save note";},1200);}));
    document.querySelectorAll("[data-company-status]").forEach(el=>el.addEventListener("change",e=>{const name=e.currentTarget.dataset.companyStatus,key=companyKey(state.candidate,name);state.saved.companies[key]={...(state.saved.companies[key]||{}),candidate:state.candidate,company:name,status:e.currentTarget.value,updatedAt:new Date().toISOString()};persist();}));
    document.querySelectorAll("[data-tracker-candidate]").forEach(btn=>btn.addEventListener("click",()=>{state.candidate=btn.dataset.trackerCandidate;history.replaceState(null,"",`/person?candidate=${state.candidate}`);renderTracker();}));
  }
  function initReveal(){
    const targets=document.querySelectorAll(".page:not(.hidden) .reveal");
    if(window.matchMedia("(prefers-reduced-motion: reduce)").matches||!("IntersectionObserver" in window)){targets.forEach(el=>el.classList.add("visible"));return;}
    const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add("visible");observer.unobserve(entry.target);}}),{rootMargin:"0px 0px -8% 0px",threshold:.05});
    targets.forEach(el=>observer.observe(el));
  }
  let saveTimer;
  function persist(){(window.OrbitApp?.listeners||[]).forEach(f=>{try{f()}catch(e){console.error(e)}});const labels=[$("save-label"),$("tracker-save-label")].filter(Boolean);labels.forEach(el=>el.textContent="SAVING…");clearTimeout(saveTimer);saveTimer=setTimeout(async()=>{try{const r=await fetch("/api/state",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(state.saved)});if(!r.ok)throw new Error();labels.forEach(el=>el.textContent="SAVED LOCALLY");}catch{labels.forEach(el=>el.textContent="SAVE FAILED");}},180);}
  function sourceKeys(data){const map={Vaanya:[],Vrinda:[]};for(const p of data.profiles)map[p.candidate]=p.jobs.map(job=>jobIdentity(job));return map;}
  function seedSeen(){state.saved.meta||={};state.saved.meta.seen||={};state.saved.meta.newOpportunities||={};const ids=sourceKeys(state.data);let changed=false;for(const [candidate,keys] of Object.entries(ids)){if(!state.saved.meta.seen[candidate]){state.saved.meta.seen[candidate]=[...new Set(keys)];changed=true;}}if(changed)persist();}
  async function refreshSheets(button){
    const original=button.textContent;button.disabled=true;button.textContent="↻ Syncing live sheets…";
    try{const response=await fetch("/api/refresh",{method:"POST"});if(!response.ok)throw new Error((await response.json()).error||"Refresh failed");const latest=await(await fetch("/api/data?fresh="+Date.now())).json();const seen=state.saved.meta?.seen||{};const newMap=state.saved.meta?.newOpportunities||{};let added=0;
      for(const p of latest.profiles){const old=new Set(seen[p.candidate]||[]);const next=sourceKeys({profiles:[p]})[p.candidate]||[];for(const job of p.jobs){const key=jobIdentity(job);if(!old.has(key)){newMap[`${p.candidate}:${key}`]=new Date().toISOString();added++;}}seen[p.candidate]=[...new Set([...old,...next])];}
      state.saved.meta={...state.saved.meta,seen,newOpportunities:newMap};state.data=latest;persist();if(state.route==="person")renderTracker();else if(state.route!=="home")renderOpeningPage();button.textContent=latest.source_mode==="live"?(added?`✓ ${added} new row${added===1?"":"s"} found`:"✓ Live Sheets synced"):(added?`⚠ Fallback · ${added} new row${added===1?"":"s"}`:"⚠ Local workbook fallback loaded");setTimeout(()=>button.textContent=original,3000);
    }catch(error){button.textContent="Refresh failed";console.error(error);setTimeout(()=>button.textContent=original,2200);}finally{button.disabled=false;}
  }
  function openEntry(){$("entry-candidate").value=state.candidate;$("entry-date").value="";$("entry-form").reset();$("entry-candidate").value=state.candidate;$("entry-dialog").showModal();}
  function submitEntry(event){event.preventDefault();const candidate=$("entry-candidate").value,company=$("entry-company").value.trim(),title=$("entry-role").value.trim();if(!company||!title)return;const rawUrl=$("entry-url").value.trim();const url=/^https?:\/\//i.test(rawUrl)?rawUrl:"";const job={id:`manual-${Date.now()}`,candidate,company,title,location:$("entry-location").value.trim(),url,status:$("entry-status").value,experience:"",compensation:"",notes:"",applicationNotes:$("entry-notes").value.trim(),category:"Manual entry",score:"",verification:"Added in tracker",source_sheet:"Dashboard entry",source_row:null,manual:true};const key=roleKey(candidate,job);state.saved.customJobs[key]=job;state.saved.jobs[key]={candidate,status:job.status,appliedAt:job.status==="Applied"?($("entry-date").value||nowISODate()):$("entry-date").value,applicationNotes:job.applicationNotes,updatedAt:new Date().toISOString()};state.saved.meta.newOpportunities||={};state.saved.meta.newOpportunities[key]=new Date().toISOString();persist();$("entry-dialog").close();event.currentTarget.reset();state.candidate=candidate;if(state.route==="person"){renderTracker();}else{state.route=candidate.toLocaleLowerCase();goRoute(state.route);}}
  async function load(){
    const [dataResponse,stateResponse]=await Promise.all([fetch("/api/data"),fetch("/api/state")]);if(!dataResponse.ok)throw new Error("Workbook snapshot not found. Run website/export_data.py first.");state.data=await dataResponse.json();if(stateResponse.ok)state.saved={...state.saved,...await stateResponse.json()};state.saved.jobs||={};state.saved.companies||={};state.saved.customCompanies||={};state.saved.customJobs||={};state.saved.meta||={seen:{},newOpportunities:{}};
    state.route=routeFromPath();if(state.route==="vaanya"||state.route==="vrinda")state.candidate=state.route[0].toUpperCase()+state.route.slice(1);if(state.route==="person"){const requested=new URLSearchParams(location.search).get("candidate");if(["Vaanya","Vrinda"].includes(requested))state.candidate=requested;}
    seedSeen();document.querySelectorAll(".nav-link").forEach(a=>a.classList.toggle("active",a.dataset.route===state.route||(a.dataset.route==="apply"&&["vaanya","vrinda"].includes(state.route))));
    $("home-page").classList.toggle("hidden",state.route!=="home");$("today-page")?.classList.toggle("hidden",state.route!=="apply");$("hunt-page")?.classList.toggle("hidden",state.route!=="apply");$("opportunities-page").classList.toggle("hidden",!(["vaanya","vrinda"].includes(state.route)));$("tracker-page").classList.toggle("hidden",state.route!=="person");
    const companies=[...new Set(state.data.profiles.flatMap(p=>p.companies.map(c=>c.name)))].sort();$("company-options").innerHTML=companies.map(name=>`<option value="${esc(name)}"></option>`).join("");
    initReveal();
    if(state.route==="vaanya"||state.route==="vrinda"){renderOpeningPage();$("search").addEventListener("input",()=>{state.visibleCompanyLimit=12;renderOpeningPage();});$("company-filter").addEventListener("change",()=>{state.visibleCompanyLimit=12;renderOpeningPage();});$("category-filter").addEventListener("change",()=>{state.visibleCompanyLimit=12;renderOpeningPage();});$("sort-order").addEventListener("change",()=>{state.visibleCompanyLimit=12;renderOpeningPage();});$("show-more-companies").addEventListener("click",()=>{state.visibleCompanyLimit+=12;renderOpeningPage();});$("refresh").addEventListener("click",()=>refreshSheets($("refresh")));$("add-opportunity").addEventListener("click",openEntry);}
    if(state.route==="person"){renderTracker();$("tracker-search").addEventListener("input",renderTracker);$("tracker-filter").addEventListener("change",renderTracker);$("tracker-refresh").addEventListener("click",()=>refreshSheets($("tracker-refresh")));$("tracker-add").addEventListener("click",openEntry);}
  }
  $("entry-form").addEventListener("submit",submitEntry);
  $("export").addEventListener("click",()=>{if(!state.data)return;const content={candidate:state.candidate,profile:profile(state.candidate),tracker:state.saved};const blob=new Blob([JSON.stringify(content,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`${state.candidate.toLowerCase()}_opportunity_tracker.json`;a.click();URL.revokeObjectURL(a.href);});
  window.OrbitApp={state,statuses,esc,norm,logo,jobUrl,jobIdentity,roleKey,allJobs,jobState,jobStatus,getContacts,isNew,isLinkedIn,isHistorical,profile,nowISODate,dateLabel,persist,openEntry,renderTracker:()=>{if(state.route==="person")renderTracker();},refreshSheets,listeners:[],ready:false};
  load().then(()=>{window.OrbitApp.ready=true;window.dispatchEvent(new Event("orbit:ready"));}).catch(error=>{console.error(error);document.querySelector("main").insertAdjacentHTML("beforeend",`<div class="load-error">Dashboard could not load: ${esc(error.message)}</div>`);});
})();
